# Generated by Django 2.2.15 on 2020-09-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shmuels_django_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetings',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
